### ISSUE TITLE
Ability to save some cookies

### ISSUE THREAD

**Issue by B00ze64** [cpeterso/clear-flash-cookies#1]
Good day.

I haven't tried your extension yet because Better Privacy still works with my FF52ESR. But if I were to switch to Clear-Flash-Cookies, I would want the ability to save (protect) some cookies (e.g. game settings etc). Do you plan in adding this?

Thank you.

**Comment by cpeterso** [comment]
The WebExtension API ([removePluginData](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browsingData/removePluginData) and [RemovalOptions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browsingData/RemovalOptions)) provide a way to delete browsing history (such as Flash and HTTP cookies) for specific domains, but unfortunately doesn't provide a way to exclude domains from being deleted.

I submitted a feature request to Mozilla's WebExtension team because HTTP cookie deleting extensions might want to exclude some domains as you suggested.

A possible workaround might be to scan the user's browser history, make a list of every domain the user has ever visited, remove the excluded domains, and then delete Flash cookies for every remaining domain. This seems like it would be slow to do every time.

**Comment by B00ze64** [comment]
Hi. I had a look at RemovePluginData - it does not provide any way to retain specific domains; the only thing you can do is tell it to keep recent data or to remove all data + I wonder if it really knows about the Flash cookies stored in a user's profile folder; the browser would have to pass this delete request to Flash itself and Flash would be doing the deleting - does Flash do this? The workaround you suggested is bad, you would be removing the site from history. Too bad WebExtensions do not have access to the filesystem :-(

**Comment by cpeterso** [comment]
Yes, Firefox asks Flash to delete the Flash cookies (using an NPAPI C++ API called [NPP_ClearSiteData](https://searchfox.org/mozilla-central/search?case=true&q=NPP_ClearSiteData)). Firefox doesn't actually know where Flash stores its Flash cookie files.

I don't think my proposed workaround would remove the site from history. It would just create a list of visited sites from history and then pass that list (minus the user's excluded sites) to removePluginData() using RemovalOptions. IIUC, that would only remove the plugin data (Flash cookies) of those sites.

**Comment by B00ze64** [comment]
Ah! I had not clicked on RemovalOptions!  I see now how you would do it. Interesting. Is there no way to ask Flash which domains it has cookies for? My history dates back many years, you would be passing a huge array to removePluginData! Is there a way to grab all history for the last session only? Also, what about opened TABs - you would want to keep those cookies around until the tab is closed...

**Comment by cpeterso** [comment]
> Is there a way to grab all history for the last session only?

That is an interesting question. When the extension is first installed, it could scan the entire browsing history and remember the current scan time (using the WebExtension [storage API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage)). In the future, the extension could just scan the browsing history since the last scan time (i.e. the last session) and then update the stored scan time for the next session.

That might not be took inefficient. I'm not sure what a good UI would look like. Perhaps just a text field with a list of comma-separated domain names.

**Comment by B00ze64** [comment]
Yup, if you can only pass the domains from the last session minus those whitelisted, minus, if possible, those with opened tabs, then it would be pretty efficient. As for the UI, if you can, make it a list-view, in case someone wants to whitelist lots of domains; a textfield is fine for up to say 6 domains, but once it scrolls off the visible portion, it becomes a pain. Thanks for thinking of this!

**Comment by B00ze64** [comment]
Hmm, I had a look at RemovalOptions again. It says "This property only applies to cookies and local storage items" - Maybe it will not work for Flash cookies?

**Comment by cpeterso** [comment]
> I had a look at RemovalOptions again. It says "This property only applies to cookies and local storage items" - Maybe it will not work for Flash cookies?

That would not surprise me. Firefox doesn't delete the Flash cookie files itself. It calls a Flash C++ API ([NPP_ClearSiteData](https://searchfox.org/mozilla-central/search?case=true&q=NPP_ClearSiteData)), asking Flash to clean up its Flash cookies. Perhaps Flash and the NPP_ClearSiteData API doesn't support all the same RemovalOptions that Firefox can for regular cookies and local storage.

**Comment by cpeterso** [comment]
Closing this issue because this extension is no longer relevant now that Adobe and Mozilla have EOL'd Flash.
